baseurl = "https://16430104.xyz"
languageCode = "zh-cn"
title = "techstay的未和谐空间"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

hasCJKLanguage = true

disqusShortname = "techstay-blog"

googleAnalytics = "G-7D2YXGM78T"
[pagination]
pagerSize = 5
