# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
favicon = "/favicon.ico"
rssFullContent = true

[footer]
customText = 'æœ¬ç«™æ€»è®¿é—®é‡<span id="vercount_value_site_pv">Loading</span>æ¬¡ï¼Œæ€»è®¿å®¢æ•°<span id="vercount_value_site_uv">Loading</span>äººï¼Œå½“å‰é¡µé¢è®¿é—®é‡<span id="vercount_value_page_pv">Loading</span>æ¬¡'
since = 2020

[dateFormat]
lastUpdated = "Jan 02, 2006 15:04 MST"
published = "Jan 02, 2006"

[sidebar]
emoji = "ğŸµ"
subtitle = "æƒ³è¯´çš„è¯æœ‰å¾ˆå¤š"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.webp"

[article]
headingAnchor = true
math = true
readingTime = true

[article.license]
default = 'Licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh">CC BY-NC-ND 4.0</a>'
enabled = true

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
card = "summary_large_image"
site = ""

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
default = "auto"
toggle = true

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
admin = ""
adminLabel = ""
apiKey = ""
apiUrl = ""
shortname = ""

[comments.utterances]
issueTerm = "pathname"
label = ""
repo = ""

[comments.remark42]
host = ""
locale = ""
site = ""

[comments.vssue]
autoCreateIssue = false
clientId = ""
clientSecret = ""
owner = ""
platform = ""
repo = ""

[comments.waline]
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
lang = ""
placeholder = "èæ°´ç›¸é€¢ä¸æ˜“ï¼ŒæŒ‡é—´ç‚¹ç‚¹ç•™æ„"
requiredMeta = ["name", "email", "url"]
serverURL = "https://waline.16430104.xyz"
visitor = "æ¸¸å®¢"

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
lang = ""
path = ""
region = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
category = ""
categoryID = ""
darkTheme = ""
emitMetadata = 0
lightTheme = ""
mapping = ""
reactionsEnabled = 1
repo = ""
repoID = ""

[comments.gitalk]
admin = ""
clientID = ""
clientSecret = ""
owner = ""
repo = ""

[comments.cusdis]
host = ""
id = ""
